### ISSUE TITLE
unused argument: cutoff.features_annotation

### ISSUE THREAD

**Issue by luca-dex** [caravagn/revolver#11]
In `rev_analyzer.R` there is a call to `revolver_plt_group_trajectories` that pass as argument `cutoff.features_annotation` which is not defined for this function.

Shouldn't it be `cutoff.edges_annotation` ?

https://github.com/caravagn/revolver/blob/master/R/rev_analyzer.R#L290

**Comment by caravagn** [comment]
Luca, can you run also `revolver_plt_dendogram` 4 lines above this bug? I think that's a typo as well.

**Comment by caravagn** [comment]
@ttriche/ @luca-dex you fixed this with your merge request is this correct?

**Comment by luca-dex** [comment]
yes, closed with #12
