### ISSUE TITLE
Function define twice

### ISSUE THREAD

**Issue by luca-dex** [caravagn/revolver#15]
The function `plot.rev_cohort_fit` is defined twice. In `lib_plot_fit.R` and in `rev_fit.R`.

**Comment by caravagn** [comment]
Luca, can you check if they are the same definition and in case keep just one of the two?

**Comment by luca-dex** [comment]
The have different signatues, and different content:

In `rev_fit.R`:
```R
plot.rev_cohort_fit = function(x,
    patients = x$patients,
    merge.files = FALSE,
    cex = 1)
```

In `plot.rev_cohort_fit.R`:
```R
plot.rev_cohort_fit = function(x,
    patients = names(x$fit$phylogenies),
    plot.stat = TRUE,
    palette = 'Set1',
    out.file = 'REVOLVER-cohort.pdf',
    layout = paste(length(patients), 'x1', sep =''),
    alpha = 0.7,
    verbose = FALSE,
    ...
)
```

**Comment by caravagn** [comment]
I should have identified the most up to date implementation as the one in `rev_fit.R`. I commented out the other one and I can close this issue.
