### ISSUE TITLE
Variable not defined

### ISSUE THREAD

**Issue by luca-dex** [caravagn/revolver#16]
The variable `PATIENT` is not defined in function `plotCCFTrees`

**Comment by caravagn** [comment]
Hi Luca, is there a fast way to look at all the R sources of the package and see if there are some functions which are *never* called? I think there are some leftover from previous versions of the tool (`plotCCFTrees` being one of those).

**Comment by luca-dex** [comment]
mmm... It'm using the R CMD check to get the list of variables and function not defined

**Comment by caravagn** [comment]
I think that we can close this one once we have sucessfully 1) merged the current branch for clonevo to master, and 2) cancelled file lib_clonevo.R. These undefined functions come out of that tool, where code is not very clearly organized and I had difficulties chopping it properly.
