### ISSUE TITLE
Crash during phylogenetic trees reconstruction

### ISSUE THREAD

**Issue by danro9685** [caravagn/revolver#18]
The function revolver_compute_CLtrees may lead to the following error during phylogenetic trees reconstruction: Error in M[colnames(MI.table), colnames(MI.table)]

To reproduce the error, see the attached RData [cohort.RData.zip](https://github.com/caravagn/revolver/files/2499621/cohort.RData.zip) and the following block of code: 

```
library("revolver")
load("cohort.RData")
cohort = revolver_compute_CLtrees(
    cohort, 
   "TCGA-OR-A5L8", 
    options = list(sspace.cutoff = 10000,
                   n.sampling = 5000,
                   store.max = 200,
                   overwrite = FALSE))
```

**Comment by xtmgah** [comment]
Hello, I am using revolver for our multiple region WGS data and we have the same issue here. Do you have any solution for this issue? Thanks.

**Comment by caravagn** [comment]
Hi @danro9685, I think that your input data is inconsistent and that you are using then wrong function here I will add more checks to the input to raise errors in cases like yours, where the `$dataset` field reports 2 distinct clusters, both of them clonal. 

See: `print(cohort$dataset)`

That's wrong, you only have one clonal cluster (unless you have multiple cells of origin which is not possible in the current implementation of the tool). Besides, you are asking to construct a CL tree, while your data is of CCF type, and thus you should use `revolver_compute_phylogenies` as the main call to create a tree.

This runs smooth.

`load("~/Downloads/cohort.RData")`
`cohort$dataset$cluster = 1`
`revolver::revolver_compute_phylogenies(x = cohort, patient = 'TCGA-OR-A5L8')`.

@xtmgah Do you have exactly the same issue here? What is the content of your dataset field in the cohort object?
