### ISSUE TITLE
Crash txtProgressBar

### ISSUE THREAD

**Issue by danro9685** [caravagn/revolver#19]
The function revolver_compute_CLtrees can crash due to txtProgressBar: Error in txtProgressBar(min = 0, max = length(TREES), style = 3) :  must have 'max' > 'min'

To reproduce the error, see the attached RData [cohort.RData.zip](https://github.com/caravagn/revolver/files/2499631/cohort.RData.zip) and the following block of code: 

```
library("revolver")
load("cohort.RData")
cohort = revolver_compute_CLtrees(
    cohort, 
   "TCGA-C8-A26V", 
    options = list(sspace.cutoff = 10000,
                   n.sampling = 5000,
                   store.max = 200,
                   overwrite = FALSE))
```

**Comment by caravagn** [comment]
I think I just need to change all txt progress bar initializers to -1 and not 0.

**Comment by luca-dex** [comment]
if the max is 0 we can avoid to draw the bar, can't we?
