### ISSUE TITLE
Revolver_analyzer

### ISSUE THREAD

**Issue by xtmgah** [caravagn/revolver#24]
Hello:

I am trying to run the Revolver analyzer in our multiple region lung cancer study (59 subjects and 150 samples). I am trying to use the Revolver_analyzer and looks it's take more than 1 day and it's still running. Do you how idea how lung it will take for such large sample size? And after then function of Revolver analyzer, how do I make a plot like the major figures in nature methods? 

I tested the examples use the CRC dataset and after Revolver analyzer, but these is no similar figures like that. Also I  try to load the 'Drivers_all_standard_parameters/Drivers_all_standard_parameters/CRC-Cross.fit.RData', but looks like it only have a objects input_list:

> input_list
[[1]]
list

[[2]]
fit

So, how to I pull out the fit object and plot using revolver_plt_rclusters? 

Thanks for your help.

**Comment by caravagn** [comment]
Hi @xtmgah, it is weird it runs so long. With the TRACERx cohort, which is 100 patients and more than 65K mutations, tree generations took about ~30 minutes on a standard laptop, and REVOLVER fit a few mins. There might be something odd with the object that you are processing. What is the number of mutations, drivers, samples, etc? 

Besides, my suggestion is to follow the CRC vignette [CRC vignette](https://github.com/caravagn/revolver.misc/blob/master/vignette_CRC_Cross_et_al/vignette_CRC_Cross_et_al.md) and avoiding to use the `analyzer` function. The reason is that `analyzer` will collapse several steps of analysis at once, which is good and fast if you know what you are doing. If you instead run then analysis for the first time, and you need to debug it as in your case, you should call the relevant functions step by step as in the vignette, so that you can easily understand what the problem is (if any). 

Beware that the CRC vignette works with binary data, not CCF, and thus uses `revolver_compute_CLtrees ` to create trees. If you use CCF you have to call `revolver_compute_phylogenies`, all the rest is unchanged.

**Comment by xtmgah** [comment]
I think the program is fine. It's just take a long time to build phylogenetic tree (specially for the subject with up to 10 regions, which have identified more than 15 subclone cluster)... I run the step by step and looks have the same output....So, I think I have to wait...

**Comment by caravagn** [comment]
Well I see, the sample with 15 clones will take a lot of time to compute the tree, compared to the others ... it might be that one, let me know if that stops anytime soon otherwise I suggest you to prioritize the analysis of some of those clusters. Maybe keeping only clusters with a putative driver annotated inside would be a reasonable way to subset them. Another option to debug REVOLVER is removing that patient from a preliminary analysis (or any other patient with that very large number of clusters), and running the tool on the others.

**Comment by xtmgah** [comment]
Hello Caravagn:

Thanks fro your previous help. the program are finally finish by using step-by-step method. However, I can't make the finally heatmap plot using the finally plot function: revolver_plt_rclusters

> revolver_plt_rclusters(fit, 
+                        cutoff.features_annotation = 1,file = 'cluster.pdf')
 [ REVOLVER Plot: REVOLVER Cluster table with features table ] 
	 Cutoff to annotate features (min. observations) = 1  
	 Output file = cluster.pdf  
**Error in 1:nrow(edges) : argument of length 0**

Do you have any idea? 

Here are the fit result:

> fit
 [ REVOLVER  1.0 ~ "Haggis and tatties" ] 

	 LUSC and LUNE cohort of lung cancer 

	 Patient IDs     : IGC-02-1001,  IGC-02-1016,  IGC-02-1017,  IGC-02-1025,  IGC-02-1029,  IGC-02-1074,  ...
	 Cohort size     : 58 patients, 3279 alterations, 751 drivers
	 Drivers         : ABL1,  AKAP9,  C10orf71,  CACNA1E,  CDH6,  CEP192,  ... 

	----------------------
	Computations available
	----------------------

	 Trees per patient    : YES
	 Fit via TL           : YES
	 REVOLVER clustering  : YES
	 Jackknife statistics : NO

	---------------------------
	Summary for data and models
	---------------------------

	 IGC-02-1001 :  k =  31 | t =  31 | n =  5 | r =  3 | m =   52 | d = 40 	[ Fit ]  # 1   | g =  3.3e-01 | f =  9.9e-03   [ Cluster C1 ]
	 IGC-02-1016 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   73 | d = 59 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1017 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   67 | d = 59 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1025 :  k =   1 | t =   1 | n =  1 | r =  2 | m =   19 | d = 16 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1029 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   95 | d = 79 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1074 :  k =  11 | t =  11 | n =  5 | r =  1 | m =   37 | d = 33 	[ Fit ]  # 1   | g =    1e+00 | f =  8.3e-02   [ Cluster C1 ]
	 IGC-02-1097 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   42 | d = 33 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1105 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   28 | d = 23 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1169 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   49 | d = 38 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-02-1212 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   26 | d = 18 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-03-1026 :  k =   4 | t =   2 | n =  5 | r =  2 | m =   84 | d = 72 	[ Fit ]  # 1   | g =  2.5e-01 | f =  4.2e-02   [ Cluster C1 ]
	 IGC-03-1049 :  k =   1 | t =   1 | n =  3 | r =  3 | m =   43 | d = 34 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-03-1076 :  k = 200 | t = 200 | n =  8 | r =  6 | m =   43 | d = 36 	[ Fit ]  # 140   | g =  9.3e-02 | f =  4.8e-06   [ Cluster C2 ]
	 IGC-03-1088 :  k =  17 | t =  12 | n =  7 | r =  4 | m =   33 | d = 23 	[ Fit ]  # 16   | g =  1.9e-01 | f =  2.9e-03   [ Cluster C2 ]
	 IGC-03-1254 :  k =   3 | t =   3 | n =  4 | r = 10 | m =   28 | d = 25 	[ Fit ]  # 2   | g =    3e-01 | f =  7.5e-02   [ Cluster C1 ]
	 IGC-03-1263 :  k = 200 | t =  39 | n = 10 | r =  7 | m =   68 | d = 54 	[ Fit ]  # 72   | g =    2e-01 | f =  1.1e-04   [ Cluster C1 ]
	 IGC-03-1265 :  k = 200 | t = 200 | n = 16 | r =  7 | m =   52 | d = 44 	[ Fit ]  # 26   | g =  6.4e-03 | f =  2.7e-14   [ Cluster C2 ]
	 IGC-03-1267 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   62 | d = 53 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-03-1294 :  k =  60 | t =  20 | n =  7 | r =  6 | m =   87 | d = 75 	[ Fit ]  # 48   | g =  1.2e-01 | f =  7.9e-04   [ Cluster C1 ]
	 IGC-03-1321 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   21 | d = 19 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-03-1328 :  k = 200 | t = 200 | n =  6 | r = 10 | m =   29 | d = 27 	[ Fit ]  # 47   | g =  1.8e-01 | f =    2e-04   [ Cluster C2 ]
	 IGC-04-1041 :  k =   8 | t =   2 | n =  7 | r =  3 | m =   71 | d = 58 	[ Fit ]  # 7   | g =  4.4e-01 | f =  2.5e-02   [ Cluster C1 ]
	 IGC-04-1089 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   44 | d = 33 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-04-1154 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   73 | d = 60 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-04-1164 :  k =   1 | t =   1 | n =  2 | r =  1 | m =  341 | d = 264 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C0 ]
	 IGC-04-1189 :  k =   1 | t =   1 | n =  1 | r =  1 | m =    3 | d =  3 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-08-1024 :  k =   1 | t =   1 | n =  1 | r =  2 | m =   34 | d = 34 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-08-1089 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   23 | d = 18 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-09-1008 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   87 | d = 76 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-09-1042 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   35 | d = 28 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-09-1086 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   64 | d = 57 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-09-1113 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   16 | d = 15 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-10-1021 :  k = 200 | t = 120 | n = 12 | r =  4 | m =   60 | d = 49 	[ Fit ]  # 188   | g =  8.9e-02 | f =  1.1e-05   [ Cluster C1 ]
	 IGC-10-1037 :  k =  16 | t =  16 | n =  7 | r =  3 | m =   92 | d = 76 	[ Fit ]  # 11   | g =  2.2e-01 | f =  1.2e-02   [ Cluster C1 ]
	 IGC-10-1044 :  k =   1 | t =   1 | n =  1 | r =  2 | m =   50 | d = 44 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-10-1045 :  k =   8 | t =   8 | n =  8 | r =  3 | m =   43 | d = 39 	[ Fit ]  # 7   | g =  2.2e-01 | f =  2.8e-02   [ Cluster C1 ]
	 IGC-10-1055 :  k =   1 | t =   1 | n =  3 | r =  3 | m =   83 | d = 72 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-10-1061 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   33 | d = 32 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-10-1141 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   14 | d = 12 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-10-1180 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   40 | d = 34 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-10-1185 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   58 | d = 47 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-11-1053 :  k = 200 | t =  96 | n =  9 | r =  5 | m =   60 | d = 48 	[ Fit ]  # 122   | g =  1.2e-01 | f =  1.8e-05   [ Cluster C1 ]
	 IGC-11-1085 :  k = 173 | t = 173 | n = 10 | r =  5 | m =  252 | d = 176 	[ Fit ]  # 113   | g =  2.6e-02 | f =  7.1e-06   [ Cluster C1 ]
	 IGC-11-1087 :  k =   4 | t =   2 | n =  4 | r =  3 | m =   51 | d = 43 	[ Fit ]  # 2   | g =  6.7e-01 | f =  2.2e-01   [ Cluster C2 ]
	 IGC-11-1108 :  k =   1 | t =   1 | n =  1 | r =  2 | m =   47 | d = 40 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-11-1120 :  k =   2 | t =   2 | n =  4 | r =  1 | m =   40 | d = 30 	[ Fit ]  # 1   | g =    1e+00 | f =    5e-01   [ Cluster C1 ]
	 IGC-11-1128 :  k =   1 | t =   1 | n =  2 | r =  8 | m =    4 | d =  4 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-11-1132 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   34 | d = 26 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-12-1069 :  k =   1 | t =   1 | n =  3 | r =  2 | m =   52 | d = 38 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-12-1086 :  k =   1 | t =   1 | n =  2 | r =  1 | m =   76 | d = 62 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-12-1088 :  k =   4 | t =   4 | n =  5 | r =  2 | m =   94 | d = 78 	[ Fit ]  # 2   | g =    5e-01 | f =  1.1e-01   [ Cluster C1 ]
	 IGC-12-1114 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   61 | d = 49 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]
	 IGC-13-1081 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   31 | d = 28 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-13-1146 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   42 | d = 37 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-13-1166 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   11 | d =  9 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-13-1174 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   53 | d = 46 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C1 ]
	 IGC-13-1182 :  k =   1 | t =   1 | n =  1 | r =  1 | m =   30 | d = 21 	[ Fit ]  # 1   | g =    1e+00 | f =    1e+00   [ Cluster C2 ]

	Legend 
		 k : phylogenies  
		 t : combinations of information transfer 
		 n : groups (nodes of the tree) 
		 r : regions (inputs per patient) 
		 m : number of alterations 
		 d : number of driver alterations
		 # : number of the solution selection (out of k)  
		 g : goodness-of-fit 
		 f : score of the model

	--------------------
	Summary for clusters
	--------------------

	   C1 :  n =    1 | jackknife =   NA
	   C2 :  n =   42 | jackknife =   NA
	   C0 :  n =   14 | jackknife =   NA

	Legend 
		         n : number of patients in the cluster
