### ISSUE TITLE
E: Error in M[df[i, "from"], df[i, "to"]] : subscript out of bounds

### ISSUE THREAD

**Issue by nilcampaHU** [caravagn/revolver#26]
Hello, revolver gives this error after doing all previous steps correctly. Context:

```
1] Model selection via Expectation Maximization  

        Number of Solutions 200|   2| 200| 200|  60| 200|
   Combinations of Transfer   2|   1|  28|   1|   1|  10|

                       Initialization 179|   2| 161| 190|  53| 174|

# 1    : 	E: Error in M[df[i, "from"], df[i, "to"]] : subscript out of bounds
```

I'd like some help. Thanks

**Comment by caravagn** [comment]
Hi @nilcampaHU thanks for the issue. 

It's hard for me to say why there is an error with no information on the data etc. Did you have a look at the trees that you have in each patient, before running the fit? How do they look like?

**Comment by nilcampaHU** [comment]
Hi, that's true I didn't check if the trees were correctly generated. I used the revolver_analyzer function wrapper and it didn't give me any error in the previous steps so I didn't think about it.

Now I tried to generate a rev_cohort object with the trees using revolver_compute_phylogenies. It gives the following error: 
```
------------------------------------------------------------------
Creating rev_phylo object for REVOLVER (this might take some time)
------------------------------------------------------------------
Total number of trees with non-zero scores is 4091 -- too many, storing top 100 
  |=================================================================================================================================================| 100%
Error in rev_count_information_transfer_comb(x, patient) : 
  p %in% names(x$phylogenies) is not TRUE
```

I think revolver should've created the x$phylogenies before, but for some reason it's obviously not doing it. I have no idea of what's the problem.

Thanks for your help.

**Comment by caravagn** [comment]
I suggest you to use that function only when you have checked that your analysis is going smooth in all its steps. 

It seems that there're errors in the generation of trees for that particular patient, have you had a look at its data? My suggestion is to check 1) wether clones are properly defined, 2) driver mutations are annotated etc. There are functions to plot the data that might help you visualize easily that. 

By the way, the function crashing is supposed to count the different configurations of transfer for the trees of this particular patient. I am happy to help you out more, but I'd need to see the data at least for this patient? You can write me privately if you wish.

**Comment by nilcampaHU** [comment]
Thanks for your help. I tried the function with many different patients and it's giving the error with all of them. The problem might actually by an insufficiently filtered/curated data. However, running clonevol alone (the original tool) does generate trees correctly.

> I'd need to see the data at least for this patient? You can write me privately if you wish.

Unfortunately, I can't send you the data to check what's the issue. 

In the other hand, I've already run clonevol with all those patients, and I have their trees. Probably would be a lot easier for me to directly use those trees. The function 'revolver_compute_phylogenies' has the option 'precomputed.trees' to give revolver already computed trees. 
What I don't know is how to get the 'adjacency matrices' of the trees from clonevol. 
Is there any direct way to get these matrices from clonevol?

Thank you

**Comment by caravagn** [comment]
If all your patients fail I think you're shaping the input data in the wrong format. I can't suggest more than looking at the vignette to see examples of correct data formats and check differences to your inputs, or sharing anonymized screenshots of data heatmaps.

Concerning clonevol trees, as we explain the paper that tool will construct - at the end of its second computation step -  only 1 single tree per patient, or fail. To make sense of revolver, however, you want instead to have several trees per patient and do model selection (if you have 1 tree there's no option to choose). For this reason the tool wraps clonevol, but skips its second step and returns several trees per patient.

You should therefore find a way to get those trees inspecting clonevol code, or do the effort to write proper inputs so that the tool will do the job for you.
