### ISSUE TITLE
Cannot Load Data

### ISSUE THREAD

**Issue by EvelyneCalista** [caravagn/revolver#33]
Dear Mr. Caravagna,

I would like to load the data after install Revolver, but it said the dataset is not found.
Do I need to install other package for the data?
Thank you.

![image](https://user-images.githubusercontent.com/71305979/93163437-b8017d00-f749-11ea-893d-e73ff68df16a.png)

**Comment by caravagn** [comment]
Hello, did you see [https://caravagn.github.io/revolver/articles/Cross_CRC_MSeq.html](this vignette)?

**Comment by EvelyneCalista** [comment]
Thank you Mr. Caravagna
