### ISSUE TITLE
How to use CNA data in construction of phylogenetic tree ?

### ISSUE THREAD

**Issue by qindan2008** [caravagn/revolver#37]
I used Sclust (https://www.nature.com/articles/nprot.2018.033) for allele-specific clonal and subclonal copy numbers analysis. But how can I feed the information from Sclust into revolver? I need to construct a phylogenetic tree based on both SNV and CNA. I have performed clustering of SNV with pyclone.  

How to get the CCF of CNAs? And how to assign the CNA regions to SNV cluster? I have learned, for clone regions, they should have the same CCF value and the same cluster ID with clonal SNVs. But how to deal with subclone regions? 

And, if a region is clonal just in primary sample not in metastatic sample? How to deal with this situation?
Subclone calls from patient S01 metastatic sample:
[S01M_subclone_cn.txt](https://github.com/caravagn/revolver/files/6065877/S01M_subclone_cn.txt)
SCNA calls from patient S01 metastatic sample:
[S01M_SCNA.txt](https://github.com/caravagn/revolver/files/6065879/S01M_SCNA.txt)
SCNA calls from patient S01 primary sample:
[S01P_SCNA.txt](https://github.com/caravagn/revolver/files/6065880/S01P_SCNA.txt)
Subclone calls from patient S01 primary sample:
[S01P_subclone_cn.txt](https://github.com/caravagn/revolver/files/6065881/S01P_subclone_cn.txt)

Thank you very much.

**Comment by caravagn** [comment]
Dear @qindan2008, the point of revolver is to have a list of mutations with associated CCF in input, so I think you have to assign SNVs (or whatever mutations you want to use ) to your CNA calls if you wish to integrate everything. I am not expert in subclonal CNA calling, so I do not know if Sclust provide you with this information. Maybe you want to read [some review on this topic](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5538405/) to creare the correct input for your analysis.

**Comment by qindan2008** [comment]
OK, thank you very much.
