### ISSUE TITLE
should I include the synonymous mutation in the input of revolver?

### ISSUE THREAD

**Issue by Yunuuuu** [caravagn/revolver#48]

**Comment by Yunuuuu** [comment]
After searching some place, like https://github.com/caravagn/revolver.misc/blob/master/vignette_TRACERx_Hanjani_et_al/vignette_TRACERx_Hanjani_et_al.Rmd, It seems we should include all mutation (both synonymous and non-synonymous) for the pipeline. But `synonymous` just won't provide advance for the evolution since synonymous mutation won't change the coded amino acid, is there any considerations for this concerns in revolver pipeline?

**Comment by caravagn** [comment]
Hello @Yunuuuu. Everything is fine; all mutations (syn and non-syn) are used to determine subclonal clusters from VAFs, and eventually imputed inside REVOLVER. The correlated information is the one of "driver" mutations, which you are supposed to annotate yourself, and that most likely will be associated to non-syn mutations.

Hope this makes sense.

**Comment by Yunuuuu** [comment]
Thanks for your explain @caravagn
