### ISSUE TITLE
devtools::install_github raises permission errror?

### ISSUE THREAD

**Issue by sunPi** [caravagn/revolver#49]
Hello,

I'm trying to install your package and I'm getting a HTTP error 404: failed to install 'unknown package' from GitHub. I checked and all spelling is correct (I literally just copied the code from your git readme):

# install.packages("devtools")
devtools::install_github("caravagnalab.github.io/revolver")

Do I need some sort of permission to install this?

**Comment by caravagn** [comment]
Can you try 

```
devtools::install_github("caravagnalab/revolver")
```

**Comment by sunPi** [comment]
Thanks, worked like a charm!
