### ISSUE TITLE
meaning of "min_counts > x" in plot_trajectories_per_cluster

### ISSUE THREAD

**Issue by sunPi** [caravagn/revolver#51]
Can you please confirm that in the plot below, the "trajectories observed > 3 times" means 4 times or more?

![image](https://github.com/caravagnalab/revolver/assets/36133841/5838c8a6-2fa6-48a2-abc7-ba1aaa3df86a)

And so for example, if I want to get trajectories found in at least 3 patients or more, then I have to set x = 2 (as in > 2)?

**Comment by caravagn** [comment]
Hi @sunPi, yes, $x>3$ is the inequality meaning at least 4 times.

**Comment by sunPi** [comment]
Thanks, @caravagn!
