### ISSUE TITLE
Concern running revolver_analyzer() on the package provided data

### ISSUE THREAD

**Issue by sahandk** [caravagn/revolver#7]
I tried the below call for the TRACERx data that you provide in the REVOLVER package:

`> revolver_analyzer(TRACERx, 
type = 'CCF', 
cohort.name = 'TRACERx', 
folder.output = "RevolverTest",
do.plots = TRUE,
options.trees = list(
sspace.cutoff = 10000, 
n.sampling = 5000, 
store.max = 200, 
overwrite = FALSE),
options.fit = list(
initial.solution = NA, 
transitive.orderings = FALSE, 
restarts = 10),
options.clustering.withGL = list(
transitive.closure = FALSE, 
min.group.size = 3, 
hc.method = 'ward', 
cutoff.features_annotation = 1, 
split.method = 'cutreeHybrid'),
options.clustering.withoutGL = list(
transitive.closure = FALSE, 
min.group.size = 3, 
hc.method = 'ward', 
cutoff.features_annotation = 1, 
split.method = 'cutreeDynamic'))`

And I got the following output:

[ REVOLVER Analyzer ] 
	 Type of tree = CCF  
	 Cohort = TRACERx  
	 Output folder = RevolverTest  
	 Perform plots = TRUE  

\-----------------------------------------------------------------------------
Analyzer: starting creating trees per patient (this might take some time ...)
\-----------------------------------------------------------------------------
 [ REVOLVER Save file ] 
 What = Output object with trees saved to file 	 - 
                                 size mode               mtime
TRACERx.phylogenyTrees.RData 56 bytes  666 2018-09-14 01:07:12
 Path: C:/Users/Sahand/RevolverTest 

\-------------------------------
Analyzer: fitting model to data
\-------------------------------
REVOLVER  --  
**Error in split.default(x$dataset, f = x$dataset$patientID) : 
  first argument must be a vector**

I am wondering if the error is because I should perform some preprocessing on TRACERx data.frame before calling the `revolver_analyzer()` function? Thanks.

**Comment by caravagn** [comment]
Hello, I am quite surprised of some of the output shown.

-----
What = Output object with trees saved to file -
size mode mtime
TRACERx.phylogenyTrees.RData 56 bytes 666 2018-09-14 01:07:12
Path: C:/Users/Sahand/RevolverTest
-----

what input did you use to run the analyzer function? Can you post the output of  `head(TRACERx)`>

**Comment by sahandk** [comment]
Hello. Below is the format of the output of `head(TRACERx)`:
```
                         Misc patientID variantID cluster is.driver is.clonal               CCF
32768   CRUK0001:7:47971467:C  CRUK0001    PKD1L1       1     FALSE     FALSE R1:0.86;R2:0;R3:0
32803  CRUK0001:21:47754753:C  CRUK0001      PCNT       1     FALSE     FALSE R1:0.86;R2:0;R3:0
32823  CRUK0001:22:37331483:G  CRUK0001    CSF2RB       1     FALSE     FALSE R1:0.86;R2:0;R3:0
32834 CRUK0001:10:102824636:G  CRUK0001   KAZALD1       1     FALSE     FALSE R1:0.86;R2:0;R3:0
32836   CRUK0001:7:81978881:C  CRUK0001  CACNA2D1       1     FALSE     FALSE R1:0.86;R2:0;R3:0
32838  CRUK0001:1:201843493:G  CRUK0001      IPO9       1     FALSE     FALSE R1:0.86;R2:0;R3:0
```

**Comment by caravagn** [comment]
Are you following the [TRACERx vignette](https://github.com/caravagn/revolver.misc/blob/master/vignette_TRACERx_Hanjani_et_al/vignette_TRACERx_Hanjani_et_al.md)?

If yes, the call to `revolver_analyzer` is using a `TRACERx.COHORT` variable, which is the result of calling some other functions on the `TRACERx` dataframe that you are instead using. I get the same error if I skip the steps in section 

>Preliminaries: checking the cohort

and try to run your code. As a suggestion, I would run first the step-by-step analysis (which is documented in the vignette) so you get to understand exactly what the tool is computing.

**Comment by sahandk** [comment]
Yes, I was trying to follow the vignette, but looks like I misunderstood the format of `TRACERx` dataframe. Thanks for the clarification.

**Comment by caravagn** [comment]
No problem, I will close this issue but let me know if you can successfully run the analysis.
